name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name:  Install dependencies
        run: npm install
      - name: Run linters
        run: npm run lint
      - name: Run formatters
        run: npm run format
      - name: Run unit tests
        run: npm run test
      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
